from pathlib import Path

_TYPE_TO_EXTS = {
    "actionscript": ["as"],
    "ada": ["adb", "ada", "ads"],
    "adoc": ["adoc"],
    "apache": ["apacheconf"],
    "apex": ["cls", "apex", "trigger"],
    "applescript": ["applescript", "scpt"],
    "bash": ["sh", "bash"],
    "beancount": ["beancount"],
    "bibtex": ["bib"],
    "c": ["c", "h"],
    "clojure": ["clj", "cljs", "cljx"],
    "cmake": ["cmake", "cmake.in", "in"],
    "coffescript": ["coffee", "cake", "cson", "cjsx", "iced"],
    "cpp": ["cc", "cpp", "cxx", "c++", "h++", "hh", "hpp", "pc", "pcc"],
    "commonlisp": ["lisp", "cl"],
    "css": ["css"],
    "cuda": ["cu", "cuh"],
    "c_sharp": ["cs", "csx"],
    "d": ["d"],
    "dart": ["dart"],
    "diff": ["diff", "patch"],
    "django": ["jinja"],
    "dockerfile": ["Dockerfile"],
    "dos": ["bat", "cmd"],
    "dot": ["dot"],
    "elisp": ["el"],
    "elixir": ["ex", "exs"],
    "elm": ["elm"],
    "erlang": ["erl"],
    "fortran": ["f", "for", "frt", "fr", "forth", "4th", "fth"],
    "f_sharp": ["fs"],
    "go": ["go"],
    "gomod": ["mod"],
    "graphql": ["graphql"],
    "groovy": ["groovy", "gradle"],
    "haml": ["haml"],
    "handlebars": ["hbs", "handlebars"],
    "haskell": ["hs", "hsc"],
    "hcl": ["hcl", "nomad", "tf", "tfvars", "workflow"],
    "html": ["htm", "html", "xhtml"],
    "ini": ["ini", "cfg", "prefs", "pro", "properties"],
    "java": ["java"],
    "javascript": ["js", "es", "es6", "jss", "jsm"],
    "javascriptreact": ["jsx"],
    "json": ["json"],
    "json5": ["json5"],
    "jsonnet": ["jsonnet", "libsonnet"],
    "julia": ["jl"],
    "kotlin": ["kt", "ktm", "kts"],
    "less": ["less"],
    "lisp": ["lisp", "asd", "cl", "lsp", "l", "ny", "podsl", "sexp"],
    "lua": ["lua", "fcgi", "nse", "pd_lua", "rbxs", "wlua"],
    "make": ["mk", "mak", "makefile"],
    "markdown": ["md", "mkdown", "mkd"],
    "nginx": ["nginxconf"],
    "objc": ["m", "mm"],
    "ocaml": ["ml", "eliom", "eliomi", "ml4", "mli", "mll", "mly", "re"],
    "pascal": ["p", "pas", "pp"],
    "perl": ["pl", "al", "cgi", "perl", "ph", "plx", "pm", "pod", "psgi", "t"],
    "php": ["php", "phtml", "php3", "php4", "php5", "php6", "php7", "phps"],
    "powershell": ["ps1", "psd1", "psm1"],
    "protobuf": ["proto"],
    "python": ["py", "pyc", "pyd", "pyo", "pyw", "pyz"],
    "r": ["r", "rd", "rsx"],
    "repro": ["repro"],
    "rst": ["rst"],
    "ruby": [
        "rb",
        "rbi",
        "builder",
        "eye",
        "gemspec",
        "god",
        "jbuilder",
        "mspec",
        "pluginspec",
        "podspec",
        "rabl",
        "rake",
        "rbuild",
        "rbw",
        "rbx",
        "ru",
        "ruby",
        "spec",
        "thor",
        "watchr",
    ],
    "rust": ["rs", "rs.in"],
    "scala": ["sbt", "sc", "scala"],
    "scheme": ["scm", "sch", "sls", "sps", "ss"],
    "scss": ["sass", "scss"],
    "smalltalk": ["st"],
    "sql": ["sql"],
    "sqlite": ["sqlite"],
    "starlark": ["bzl", "bazel", "BUILD", "WORKSPACE"],
    "stylus": ["styl"],
    "svelte": ["svelte"],
    "swift": ["swift"],
    "thrift": ["thrift"],
    "toml": ["toml"],
    "twig": ["twig"],
    "txt": ["txt"],
    "typescript": ["ts"],
    "typescriptreact": ["tsx"],
    "vbnet": ["vb"],
    "vbscrip": ["vbs"],
    "verilog": ["v", "veo", "sv", "svh", "svi"],
    "vhdl": ["vhd", "vhdl"],
    "vim": ["vim"],
    "xml": [
        "xml",
        "adml",
        "admx",
        "ant",
        "axml",
        "builds",
        "ccxml",
        "clixml",
        "cproject",
        "csl",
        "csproj",
        "ct",
        "dita",
        "ditamap",
        "ditaval",
        "dll.config",
        "dotsettings",
        "filters",
        "fsproj",
        "fxml",
        "glade",
        "gml",
        "grxml",
        "iml",
        "ivy",
        "jelly",
        "jsproj",
        "kml",
        "launch",
        "mdpolicy",
        "mjml",
        "mod",
        "mxml",
        "nproj",
        "nuspec",
        "odd",
        "osm",
        "pkgproj",
        "plist",
        "props",
        "ps1xml",
        "psc1",
        "pt",
        "rdf",
        "resx",
        "rss",
        "scxml",
        "sfproj",
        "srdf",
        "storyboard",
        "stTheme",
        "sublime-snippet",
        "targets",
        "tmCommand",
        "tml",
        "tmLanguage",
        "tmPreferences",
        "tmSnippet",
        "tmTheme",
        "ui",
        "urdf",
        "ux",
        "vbproj",
        "vcxproj",
        "vsixmanifest",
        "vssettings",
        "vstemplate",
        "vxml",
        "wixproj",
        "wsdl",
        "wsf",
        "wxi",
        "wxl",
        "wxs",
        "x3d",
        "xacro",
        "xaml",
        "xib",
        "xlf",
        "xliff",
        "xmi",
        "xml.dist",
        "xproj",
        "xsd",
        "xspec",
        "xul",
        "zcml",
    ],
    "yaml": ["yml", "yaml"],
    "zsh": ["zsh"],
}
_EXT_TO_TYPE = {ext: kv[0] for kv in _TYPE_TO_EXTS.items() for ext in kv[1]}


def parse_ftype(file_name: str):
    ext = Path(file_name).suffix or Path(file_name).name
    if ext.startswith("."):
        ext = ext[1:]
    return _EXT_TO_TYPE.get(ext)
